phppackages:
  - php5.5-amqp
  - php5.5-amqp:i386
  - php5.5-apcu
  - php5.5-apcu:i386
  - php5.5-bcmath
  - php5.5-bcmath:i386
  - php5.5-bz2
  - php5.5-bz2:i386
  - php5.5-calendar
  - php5.5-calendar:i386
  - php5.5-cgi
  - php5.5-cgi:i386
  - php5.5-cli
  - php5.5-cli:i386
  - php5.5-common
  - php5.5-common:i386
  - php5.5-ctype
  - php5.5-ctype:i386
  - php5.5-curl
  - php5.5-curl:i386
  - php5.5-dev
  - php5.5-dev:i386
  - php5.5-dom
  - php5.5-dom:i386
  - php5.5-enchant
  - php5.5-enchant:i386
  - php5.5-exif
  - php5.5-exif:i386
  - php5.5-fileinfo
  - php5.5-fileinfo:i386
  - php5.5-fpm
  - php5.5-fpm:i386
  - php5.5-ftp
  - php5.5-ftp:i386
  - php5.5-gd
  - php5.5-gd:i386
  - php5.5-gearman
  - php5.5-gearman:i386
  - php5.5-geoip
  - php5.5-geoip:i386
  - php5.5-gettext
  - php5.5-gettext:i386
  - php5.5-gmagick
  - php5.5-gmagick:i386
  - php5.5-gmp
  - php5.5-gmp:i386
  - php5.5-http
  - php5.5-http:i386
  - php5.5-iconv
  - php5.5-iconv:i386
  - php5.5-igbinary
  - php5.5-igbinary:i386
  - php5.5-imagick
  - php5.5-imagick:i386
  - php5.5-imap
  - php5.5-imap:i386
  - php5.5-interbase
  - php5.5-interbase:i386
  - php5.5-intl
  - php5.5-intl:i386
  - php5.5-json
  - php5.5-json:i386
  - php5.5-ldap
  - php5.5-ldap:i386
  - php5.5-mailparse
  - php5.5-mailparse:i386
  - php5.5-mbstring
  - php5.5-mbstring:i386
  - php5.5-mcrypt
  - php5.5-mcrypt:i386
  - php5.5-memcache
  - php5.5-memcache:i386
  - php5.5-memcached
  - php5.5-memcached:i386
  - php5.5-mongo
  - php5.5-mongo:i386
  - php5.5-mongodb
  - php5.5-mongodb:i386
  - php5.5-msgpack
  - php5.5-msgpack:i386
  - php5.5-mysql
  - php5.5-mysql:i386
  - php5.5-mysqli
  - php5.5-mysqli:i386
  - php5.5-mysqlnd
  - php5.5-mysqlnd:i386
  - php5.5-oauth
  - php5.5-oauth:i386
  - php5.5-odbc
  - php5.5-odbc:i386
  - php5.5-opcache
  - php5.5-opcache:i386
  - php5.5-pdo
  - php5.5-pdo:i386
  - php5.5-pdo-dblib
  - php5.5-pdo-dblib:i386
  - php5.5-pdo-firebird
  - php5.5-pdo-firebird:i386
  - php5.5-pdo-mysql
  - php5.5-pdo-mysql:i386
  - php5.5-pdo-odbc
  - php5.5-pdo-odbc:i386
  - php5.5-pdo-pgsql
  - php5.5-pdo-pgsql:i386
  - php5.5-pdo-sqlite
  - php5.5-pdo-sqlite:i386
  - php5.5-pgsql
  - php5.5-pgsql:i386
  - php5.5-phar
  - php5.5-phar:i386
  - php5.5-posix
  - php5.5-posix:i386
  - php5.5-propro
  - php5.5-propro:i386
  - php5.5-pspell
  - php5.5-pspell:i386
  - php5.5-radius
  - php5.5-radius:i386
  - php5.5-raphf
  - php5.5-raphf:i386
  - php5.5-readline
  - php5.5-readline:i386
  - php5.5-recode
  - php5.5-recode:i386
  - php5.5-redis
  - php5.5-redis:i386
  - php5.5-rrd
  - php5.5-rrd:i386
  - php5.5-shmop
  - php5.5-shmop:i386
  - php5.5-simplexml
  - php5.5-simplexml:i386
  - php5.5-smbclient
  - php5.5-smbclient:i386
  - php5.5-snmp
  - php5.5-snmp:i386
  - php5.5-soap
  - php5.5-soap:i386
  - php5.5-sockets
  - php5.5-sockets:i386
  - php5.5-solr
  - php5.5-solr:i386
  - php5.5-sqlite3
  - php5.5-sqlite3:i386
  - php5.5-ssh2
  - php5.5-ssh2:i386
  - php5.5-stomp
  - php5.5-stomp:i386
  - php5.5-sybase
  - php5.5-sybase:i386
  - php5.5-sysvmsg
  - php5.5-sysvmsg:i386
  - php5.5-sysvsem
  - php5.5-sysvsem:i386
  - php5.5-sysvshm
  - php5.5-sysvshm:i386
  - php5.5-tideways
  - php5.5-tideways:i386
  - php5.5-tidy
  - php5.5-tidy:i386
  - php5.5-tokenizer
  - php5.5-tokenizer:i386
  - php5.5-uploadprogress
  - php5.5-uploadprogress:i386
  - php5.5-uuid
  - php5.5-uuid:i386
  - php5.5-wddx
  - php5.5-wddx:i386
  - php5.5-xcache
  - php5.5-xcache:i386
  - php5.5-xdebug
  - php5.5-xdebug:i386
  - php5.5-xml
  - php5.5-xml:i386
  - php5.5-xmlreader
  - php5.5-xmlreader:i386
  - php5.5-xmlrpc
  - php5.5-xmlrpc:i386
  - php5.5-xmlwriter
  - php5.5-xmlwriter:i386
  - php5.5-xsl
  - php5.5-xsl:i386
  - php5.5-yac
  - php5.5-yac:i386
  - php5.5-zip
  - php5.5-zip:i386
  - php5.5-zmq
  - php5.5-zmq:i386
  - php5.6-amqp
  - php5.6-amqp:i386
  - php5.6-apcu
  - php5.6-apcu:i386
  - php5.6-bcmath
  - php5.6-bcmath:i386
  - php5.6-bz2
  - php5.6-bz2:i386
  - php5.6-calendar
  - php5.6-calendar:i386
  - php5.6-cgi
  - php5.6-cgi:i386
  - php5.6-cli
  - php5.6-cli:i386
  - php5.6-common
  - php5.6-common:i386
  - php5.6-ctype
  - php5.6-ctype:i386
  - php5.6-curl
  - php5.6-curl:i386
  - php5.6-dev
  - php5.6-dev:i386
  - php5.6-dom
  - php5.6-dom:i386
  - php5.6-enchant
  - php5.6-enchant:i386
  - php5.6-exif
  - php5.6-exif:i386
  - php5.6-fileinfo
  - php5.6-fileinfo:i386
  - php5.6-fpm
  - php5.6-fpm:i386
  - php5.6-ftp
  - php5.6-ftp:i386
  - php5.6-gd
  - php5.6-gd:i386
  - php5.6-gearman
  - php5.6-gearman:i386
  - php5.6-geoip
  - php5.6-geoip:i386
  - php5.6-gettext
  - php5.6-gettext:i386
  - php5.6-gmagick
  - php5.6-gmagick:i386
  - php5.6-gmp
  - php5.6-gmp:i386
  - php5.6-http
  - php5.6-http:i386
  - php5.6-iconv
  - php5.6-iconv:i386
  - php5.6-igbinary
  - php5.6-igbinary:i386
  - php5.6-imagick
  - php5.6-imagick:i386
  - php5.6-imap
  - php5.6-imap:i386
  - php5.6-interbase
  - php5.6-interbase:i386
  - php5.6-intl
  - php5.6-intl:i386
  - php5.6-json
  - php5.6-json:i386
  - php5.6-ldap
  - php5.6-ldap:i386
  - php5.6-mailparse
  - php5.6-mailparse:i386
  - php5.6-mbstring
  - php5.6-mbstring:i386
  - php5.6-mcrypt
  - php5.6-mcrypt:i386
  - php5.6-memcache
  - php5.6-memcache:i386
  - php5.6-memcached
  - php5.6-memcached:i386
  - php5.6-mongo
  - php5.6-mongo:i386
  - php5.6-mongodb
  - php5.6-mongodb:i386
  - php5.6-msgpack
  - php5.6-msgpack:i386
  - php5.6-mysql
  - php5.6-mysql:i386
  - php5.6-mysqli
  - php5.6-mysqli:i386
  - php5.6-mysqlnd
  - php5.6-mysqlnd:i386
  - php5.6-oauth
  - php5.6-oauth:i386
  - php5.6-odbc
  - php5.6-odbc:i386
  - php5.6-opcache
  - php5.6-opcache:i386
  - php5.6-pdo
  - php5.6-pdo:i386
  - php5.6-pdo-dblib
  - php5.6-pdo-dblib:i386
  - php5.6-pdo-firebird
  - php5.6-pdo-firebird:i386
  - php5.6-pdo-mysql
  - php5.6-pdo-mysql:i386
  - php5.6-pdo-odbc
  - php5.6-pdo-odbc:i386
  - php5.6-pdo-pgsql
  - php5.6-pdo-pgsql:i386
  - php5.6-pdo-sqlite
  - php5.6-pdo-sqlite:i386
  - php5.6-pgsql
  - php5.6-pgsql:i386
  - php5.6-phar
  - php5.6-phar:i386
  - php5.6-phpdbg
  - php5.6-phpdbg:i386
  - php5.6-posix
  - php5.6-posix:i386
  - php5.6-propro
  - php5.6-propro:i386
  - php5.6-pspell
  - php5.6-pspell:i386
  - php5.6-radius
  - php5.6-radius:i386
  - php5.6-raphf
  - php5.6-raphf:i386
  - php5.6-readline
  - php5.6-readline:i386
  - php5.6-recode
  - php5.6-recode:i386
  - php5.6-redis
  - php5.6-redis:i386
  - php5.6-rrd
  - php5.6-rrd:i386
  - php5.6-shmop
  - php5.6-shmop:i386
  - php5.6-simplexml
  - php5.6-simplexml:i386
  - php5.6-smbclient
  - php5.6-smbclient:i386
  - php5.6-snmp
  - php5.6-snmp:i386
  - php5.6-soap
  - php5.6-soap:i386
  - php5.6-sockets
  - php5.6-sockets:i386
  - php5.6-solr
  - php5.6-solr:i386
  - php5.6-sqlite3
  - php5.6-sqlite3:i386
  - php5.6-ssh2
  - php5.6-ssh2:i386
  - php5.6-stomp
  - php5.6-stomp:i386
  - php5.6-sybase
  - php5.6-sybase:i386
  - php5.6-sysvmsg
  - php5.6-sysvmsg:i386
  - php5.6-sysvsem
  - php5.6-sysvsem:i386
  - php5.6-sysvshm
  - php5.6-sysvshm:i386
  - php5.6-tideways
  - php5.6-tideways:i386
  - php5.6-tidy
  - php5.6-tidy:i386
  - php5.6-tokenizer
  - php5.6-tokenizer:i386
  - php5.6-uploadprogress
  - php5.6-uploadprogress:i386
  - php5.6-uuid
  - php5.6-uuid:i386
  - php5.6-wddx
  - php5.6-wddx:i386
  - php5.6-xcache
  - php5.6-xcache:i386
  - php5.6-xdebug
  - php5.6-xdebug:i386
  - php5.6-xml
  - php5.6-xml:i386
  - php5.6-xmlreader
  - php5.6-xmlreader:i386
  - php5.6-xmlrpc
  - php5.6-xmlrpc:i386
  - php5.6-xmlwriter
  - php5.6-xmlwriter:i386
  - php5.6-xsl
  - php5.6-xsl:i386
  - php5.6-yac
  - php5.6-yac:i386
  - php5.6-zip
  - php5.6-zip:i386
  - php5.6-zmq
  - php5.6-zmq:i386
  - php7.0-amqp
  - php7.0-amqp:i386
  - php7.0-apcu
  - php7.0-apcu:i386
  - php7.0-apcu-bc
  - php7.0-apcu-bc:i386
  - php7.0-bcmath
  - php7.0-bcmath:i386
  - php7.0-bz2
  - php7.0-bz2:i386
  - php7.0-calendar
  - php7.0-calendar:i386
  - php7.0-cgi
  - php7.0-cgi:i386
  - php7.0-cli
  - php7.0-cli:i386
  - php7.0-common
  - php7.0-common:i386
  - php7.0-ctype
  - php7.0-ctype:i386
  - php7.0-curl
  - php7.0-curl:i386
  - php7.0-dev
  - php7.0-dev:i386
  - php7.0-dom
  - php7.0-dom:i386
  - php7.0-enchant
  - php7.0-enchant:i386
  - php7.0-exif
  - php7.0-exif:i386
  - php7.0-fileinfo
  - php7.0-fileinfo:i386
  - php7.0-fpm
  - php7.0-fpm:i386
  - php7.0-ftp
  - php7.0-ftp:i386
  - php7.0-gd
  - php7.0-gd:i386
  - php7.0-gearman
  - php7.0-gearman:i386
  - php7.0-geoip
  - php7.0-geoip:i386
  - php7.0-gettext
  - php7.0-gettext:i386
  - php7.0-gmagick
  - php7.0-gmagick:i386
  - php7.0-gmp
  - php7.0-gmp:i386
  - php7.0-http
  - php7.0-http:i386
  - php7.0-iconv
  - php7.0-iconv:i386
  - php7.0-igbinary
  - php7.0-igbinary:i386
  - php7.0-imagick
  - php7.0-imagick:i386
  - php7.0-imap
  - php7.0-imap:i386
  - php7.0-interbase
  - php7.0-interbase:i386
  - php7.0-intl
  - php7.0-intl:i386
  - php7.0-json
  - php7.0-json:i386
  - php7.0-ldap
  - php7.0-ldap:i386
  - php7.0-mailparse
  - php7.0-mailparse:i386
  - php7.0-mbstring
  - php7.0-mbstring:i386
  - php7.0-mcrypt
  - php7.0-mcrypt:i386
  - php7.0-memcache
  - php7.0-memcache:i386
  - php7.0-memcached
  - php7.0-memcached:i386
  - php7.0-mongodb
  - php7.0-mongodb:i386
  - php7.0-msgpack
  - php7.0-msgpack:i386
  - php7.0-mysql
  - php7.0-mysql:i386
  - php7.0-mysqli
  - php7.0-mysqli:i386
  - php7.0-mysqlnd
  - php7.0-mysqlnd:i386
  - php7.0-oauth
  - php7.0-oauth:i386
  - php7.0-odbc
  - php7.0-odbc:i386
  - php7.0-opcache
  - php7.0-opcache:i386
  - php7.0-pdo
  - php7.0-pdo:i386
  - php7.0-pdo-dblib
  - php7.0-pdo-dblib:i386
  - php7.0-pdo-firebird
  - php7.0-pdo-firebird:i386
  - php7.0-pdo-mysql
  - php7.0-pdo-mysql:i386
  - php7.0-pdo-odbc
  - php7.0-pdo-odbc:i386
  - php7.0-pdo-pgsql
  - php7.0-pdo-pgsql:i386
  - php7.0-pdo-sqlite
  - php7.0-pdo-sqlite:i386
  - php7.0-pgsql
  - php7.0-pgsql:i386
  - php7.0-phar
  - php7.0-phar:i386
  - php7.0-phpdbg
  - php7.0-phpdbg:i386
  - php7.0-posix
  - php7.0-posix:i386
  - php7.0-propro
  - php7.0-propro:i386
  - php7.0-pspell
  - php7.0-pspell:i386
  - php7.0-radius
  - php7.0-radius:i386
  - php7.0-raphf
  - php7.0-raphf:i386
  - php7.0-readline
  - php7.0-readline:i386
  - php7.0-recode
  - php7.0-recode:i386
  - php7.0-redis
  - php7.0-redis:i386
  - php7.0-rrd
  - php7.0-rrd:i386
  - php7.0-shmop
  - php7.0-shmop:i386
  - php7.0-simplexml
  - php7.0-simplexml:i386
  - php7.0-smbclient
  - php7.0-smbclient:i386
  - php7.0-snmp
  - php7.0-snmp:i386
  - php7.0-soap
  - php7.0-soap:i386
  - php7.0-sockets
  - php7.0-sockets:i386
  - php7.0-solr
  - php7.0-solr:i386
  - php7.0-sqlite3
  - php7.0-sqlite3:i386
  - php7.0-ssh2
  - php7.0-ssh2:i386
  - php7.0-stomp
  - php7.0-stomp:i386
  - php7.0-sybase
  - php7.0-sybase:i386
  - php7.0-sysvmsg
  - php7.0-sysvmsg:i386
  - php7.0-sysvsem
  - php7.0-sysvsem:i386
  - php7.0-sysvshm
  - php7.0-sysvshm:i386
  - php7.0-tideways
  - php7.0-tideways:i386
  - php7.0-tidy
  - php7.0-tidy:i386
  - php7.0-tokenizer
  - php7.0-tokenizer:i386
  - php7.0-uploadprogress
  - php7.0-uploadprogress:i386
  - php7.0-uuid
  - php7.0-uuid:i386
  - php7.0-wddx
  - php7.0-wddx:i386
  - php7.0-xdebug
  - php7.0-xdebug:i386
  - php7.0-xml
  - php7.0-xml:i386
  - php7.0-xmlreader
  - php7.0-xmlreader:i386
  - php7.0-xmlrpc
  - php7.0-xmlrpc:i386
  - php7.0-xmlwriter
  - php7.0-xmlwriter:i386
  - php7.0-xsl
  - php7.0-xsl:i386
  - php7.0-yac
  - php7.0-yac:i386
  - php7.0-zip
  - php7.0-zip:i386
  - php7.0-zmq
  - php7.0-zmq:i386